version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: msql_db
    restart: always
    volumes:
      - ./mysql/datadir:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db0
      - MYSQL_ROOT_PASSWORD=r0Ot
    
    networks:
      - db_net

  node:
    build: node/build_ctx
    container_name: njs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: node server.js
    restart: always
    
    depends_on:
      - db
    
    networks:
      - db_net
      - rp_net

  rp:
    build: nginx
    container_name: ngx_rp
    restart: always

    ports:
      - "8080:80"
    
    networks:
      - rp_net

networks:
  db_net:
  rp_net: